cdef extern int performWFR(unsigned char *inputFilename, 
                            unsigned char *outputFilename, 
                            int image_width, 
                            int image_height, 
                            double sigmax, 
                            double wxl,
                            double wxi,
                            double wxh, 
                            double sigmay,
                            double wyl, 
                            double wyi, 
                            double wyh, 
                            double thr)

def perform_WFR(unsigned char *inputFilename, 
                            unsigned char *outputFilename, 
                            int image_width, 
                            int image_height, 
                            double sigmax, 
                            double wxl,
                            double wxi,
                            double wxh, 
                            double sigmay,
                            double wyl, 
                            double wyi, 
                            double wyh, 
                            double thr):

    performWFR(inputFilename, 
                            outputFilename, 
                            image_width, 
                            image_height, 
                            sigmax, 
                            wxl,
                            wxi,
                            wxh, 
                            sigmay,
                            wyl, 
                            wyi, 
                            wyh, 
                            thr)
